apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerized-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerized-api
  template:
    metadata:
      labels:
        app: containerized-api
    spec:
      containers:
      - name: containerized-api
        image: gcr.io/cloud-endpoint-gke/simple-containerized-api:latest
        ports:
        - containerPort: 5000
